# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nick Cave lyric search
email: krdlrosa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Search lyrics Nick Cave has written for The Bad Seeds, Grinderman, and Carnage
baseurl: "/nick-cave"
url: "https://kdlrose.github.io" # the base hostname & protocol for your site, e.g. http://example.com
dataset: "https://github.com/kdlrose/nick-cave-lyrics"
nick: "https://nickcave.com/lyrics"
copyright: "First published: 2024 Aug"
colophon: >-
  Made by <a href="https://kdlrose.github.io">Kathryn de la Rosa</a> using <a href="https://jekyllrb.com/">Jekyll</a> and lyrics directly compiled from <a href="https://nickcave.com/lyrics">nickcave.com</a>. You can view the dataset <a href="https://github.com/kdlrose/nick-cave-lyrics">here</a>.

# Build settings
markdown: kramdown
remote_theme: kdlrose/jekyll-theme-tupelo
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
